"""Modes constants"""
MODE_MAIN_MENU = "main_menu"
MODE_DOCUMENTATION = "documentation"
MODE_CHECK_CODE = "check_code"
MODE_LESSON = "lesson"
MODE_TESTING = "testing"
MODE_ACCOUNT = "account"
MODE_HELP = "help"
MODE_COMMENT = "comments"
MODE_PREMIUM = "premium"
MODE_CODING = "coding"
